const prisma = require('../../config/database');
const { AppError } = require('../../utils/AppError');
const { PERMISSIONS, hasPermission } = require('../../config/permissions');
const { writeExcel } = require('../../services/export/excelRenderer');
const { writePDF } = require('../../services/export/pdfRenderer');
const { formatDate, formatDateTime, toNumber } = require('../../services/export/formatters');

const assertAccess = (user, permission) => {
  if (!user || !hasPermission(user.role, permission)) {
    throw new AppError('Insufficient permissions for this document', 403);
  }
};

const writeDocument = async (res, format, options) => {
  if (format === 'pdf') {
    writePDF(res, options);
    return;
  }
  await writeExcel(res, options);
};

const generatedMetadata = (user, extra = {}) => ({
  'Generated By': user?.name || user?.email || 'System',
  'Generated At': formatDateTime(new Date()),
  ...extra,
});

const exportSalesInvoice = async (id, format, user, res) => {
  assertAccess(user, PERMISSIONS.SALES_READ);
  const sale = await prisma.sale.findFirst({
    where: { id, deletedAt: null },
    include: {
      customer: true,
      lineItems: { include: { quality: true } },
    },
  });
  if (!sale) throw new AppError('Sale not found', 404);

  const columns = [
    { key: 'quality', label: 'Coal Quality', pdfWidth: 180 },
    { key: 'weight', label: 'Weight (MT)', type: 'number', align: 'right', pdfWidth: 80 },
    { key: 'rate', label: 'Rate', type: 'currency', align: 'right', pdfWidth: 75 },
    { key: 'gstRate', label: 'GST %', type: 'percent', align: 'right', pdfWidth: 60 },
    { key: 'netAmount', label: 'Amount', type: 'currency', align: 'right', pdfWidth: 90 },
  ];
  const rows = sale.lineItems.map(item => ({
    quality: item.quality?.name,
    weight: item.weight,
    rate: item.rate,
    gstRate: item.gstRate,
    netAmount: item.netAmount,
  }));

  await writeDocument(res, format, {
    title: 'Sales Invoice',
    filename: `sales-invoice-${sale.saleNumber}`,
    columns,
    rows,
    totals: { netAmount: sale.netAmount },
    metadata: generatedMetadata(user, {
      'Invoice No': sale.saleNumber,
      Date: formatDate(sale.saleDate),
      Customer: sale.customer?.name,
      GSTIN: sale.customer?.gstin || '-',
      'Paid Amount': toNumber(sale.paidAmount),
      Outstanding: toNumber(sale.outstanding),
    }),
  });
};

const exportPurchaseBill = async (id, format, user, res) => {
  assertAccess(user, PERMISSIONS.PURCHASES_READ);
  const purchase = await prisma.purchase.findFirst({
    where: { id, deletedAt: null },
    include: {
      supplier: true,
      location: true,
      lineItems: { include: { quality: true } },
    },
  });
  if (!purchase) throw new AppError('Purchase not found', 404);

  const columns = [
    { key: 'quality', label: 'Coal Quality', pdfWidth: 150 },
    { key: 'weight', label: 'Weight (MT)', type: 'number', align: 'right', pdfWidth: 70 },
    { key: 'rate', label: 'Rate', type: 'currency', align: 'right', pdfWidth: 70 },
    { key: 'freight', label: 'Freight', type: 'currency', align: 'right', pdfWidth: 70 },
    { key: 'additionalExpenses', label: 'Expenses', type: 'currency', align: 'right', pdfWidth: 70 },
    { key: 'netAmount', label: 'Amount', type: 'currency', align: 'right', pdfWidth: 85 },
  ];
  const rows = purchase.lineItems.map(item => ({
    quality: item.quality?.name,
    weight: item.weight,
    rate: item.rate,
    freight: item.freight,
    additionalExpenses: item.additionalExpenses,
    netAmount: item.netAmount,
  }));

  await writeDocument(res, format, {
    title: 'Purchase Bill',
    filename: `purchase-bill-${purchase.purchaseNumber}`,
    columns,
    rows,
    totals: {
      freight: purchase.freightTotal,
      additionalExpenses: purchase.expenseTotal,
      netAmount: purchase.netAmount,
    },
    metadata: generatedMetadata(user, {
      'Bill No': purchase.purchaseNumber,
      Date: formatDate(purchase.purchaseDate),
      Supplier: purchase.supplier?.name,
      GSTIN: purchase.supplier?.gstin || '-',
      Location: purchase.location?.name || '-',
      Outstanding: toNumber(purchase.outstanding),
    }),
  });
};

const exportPaymentReceipt = async (id, format, user, res) => {
  assertAccess(user, PERMISSIONS.PAYMENTS_READ);
  const payment = await prisma.payment.findFirst({ where: { id, deletedAt: null } });
  if (!payment) throw new AppError('Payment not found', 404);

  await writeDocument(res, format, {
    title: payment.paymentType === 'RECEIVED' ? 'Payment Receipt' : 'Payment Voucher',
    filename: `payment-${payment.id.slice(0, 8)}`,
    columns: [
      { key: 'paymentDate', label: 'Date', type: 'date', pdfWidth: 90 },
      { key: 'paymentType', label: 'Type', pdfWidth: 80 },
      { key: 'paymentMode', label: 'Mode', pdfWidth: 100 },
      { key: 'entityType', label: 'Entity', pdfWidth: 90 },
      { key: 'referenceNo', label: 'Reference', pdfWidth: 130 },
      { key: 'amount', label: 'Amount', type: 'currency', align: 'right', pdfWidth: 100 },
    ],
    rows: [payment],
    totals: { amount: payment.amount },
    metadata: generatedMetadata(user, {
      'Receipt No': payment.id.slice(0, 8).toUpperCase(),
      Notes: payment.notes || '-',
    }),
  });
};

const exportExpenseVoucher = async (id, format, user, res) => {
  assertAccess(user, PERMISSIONS.EXPENSES_READ);
  const expense = await prisma.expense.findFirst({
    where: { id, deletedAt: null },
    include: { expenseType: true },
  });
  if (!expense) throw new AppError('Expense not found', 404);

  const row = {
    expenseDate: expense.expenseDate,
    expenseType: expense.expenseType?.name,
    category: expense.category,
    referenceNo: expense.referenceNo,
    description: expense.description,
    amount: expense.amount,
  };

  await writeDocument(res, format, {
    title: 'Expense Voucher',
    filename: `expense-voucher-${expense.id.slice(0, 8)}`,
    columns: [
      { key: 'expenseDate', label: 'Date', type: 'date', pdfWidth: 80 },
      { key: 'expenseType', label: 'Type', pdfWidth: 120 },
      { key: 'category', label: 'Category', pdfWidth: 90 },
      { key: 'referenceNo', label: 'Reference', pdfWidth: 110 },
      { key: 'description', label: 'Description', pdfWidth: 170 },
      { key: 'amount', label: 'Amount', type: 'currency', align: 'right', pdfWidth: 90 },
    ],
    rows: [row],
    totals: { amount: expense.amount },
    metadata: generatedMetadata(user, { 'Voucher No': expense.id.slice(0, 8).toUpperCase() }),
  });
};

const exportInvestmentStatement = async (id, format, user, res) => {
  assertAccess(user, PERMISSIONS.INVESTMENTS_READ);
  const investment = await prisma.partnerInvestment.findFirst({
    where: { id, deletedAt: null },
    include: { partner: true, returns: true },
  });
  if (!investment) throw new AppError('Investment not found', 404);

  const rows = [
    {
      date: investment.investmentDate,
      description: 'Investment',
      amount: investment.amount,
      profitShare: investment.partner?.profitShare,
      roiPercent: investment.expectedROI,
    },
    ...investment.returns.map(r => ({
      date: r.returnDate,
      description: 'Return',
      amount: r.amount,
      profitShare: r.profitShare,
      roiPercent: r.roiPercent,
    })),
  ];

  await writeDocument(res, format, {
    title: 'Partner Investment Statement',
    filename: `investment-statement-${investment.id.slice(0, 8)}`,
    columns: [
      { key: 'date', label: 'Date', type: 'date', pdfWidth: 85 },
      { key: 'description', label: 'Description', pdfWidth: 180 },
      { key: 'amount', label: 'Amount', type: 'currency', align: 'right', pdfWidth: 110 },
      { key: 'profitShare', label: 'Profit Share', type: 'currency', align: 'right', pdfWidth: 100 },
      { key: 'roiPercent', label: 'ROI %', type: 'percent', align: 'right', pdfWidth: 80 },
    ],
    rows,
    totals: { amount: rows.reduce((s, r) => s + toNumber(r.amount), 0) },
    metadata: generatedMetadata(user, {
      Partner: investment.partner?.name,
      Terms: investment.terms || '-',
    }),
  });
};

module.exports = {
  exportSalesInvoice,
  exportPurchaseBill,
  exportPaymentReceipt,
  exportExpenseVoucher,
  exportInvestmentStatement,
};
