const { AppError } = require('../../utils/AppError');
const { hasPermission } = require('../../config/permissions');
const { writeExcel } = require('../../services/export/excelRenderer');
const { writePDF } = require('../../services/export/pdfRenderer');
const { writeCSV } = require('../../services/export/csvRenderer');
const { formatDate, formatDateTime } = require('../../services/export/formatters');
const { definitions, getReportDefinition, listReportDefinitions } = require('./report.registry');

const assertReportAccess = (user, definition) => {
  if (!user || !hasPermission(user.role, definition.requiredPermission)) {
    throw new AppError('Insufficient permissions for this report', 403);
  }
};

const buildMetadata = (query, user) => ({
  'Generated By': user?.name || user?.email || 'System',
  'Generated At': formatDateTime(new Date()),
  ...(query.from ? { From: formatDate(query.from) } : {}),
  ...(query.to ? { To: formatDate(query.to) } : {}),
});

const buildReportRows = async (definition, query) => {
  const data = await definition.fetch(query);
  let rows = data.map(definition.map);
  const q = String(query.search || '').trim().toLowerCase();
  if (q) {
    rows = rows.filter((row) =>
      Object.values(row).some((v) => String(v ?? '').toLowerCase().includes(q))
    );
  }
  const totals = definition.totals ? definition.totals(rows) : {};
  return { data, rows, totals };
};

const exportDefinition = async (definition, format, query, user, res, overrides = {}) => {
  assertReportAccess(user, definition);
  const { rows, totals } = await buildReportRows(definition, query);
  const exportOptions = {
    title: overrides.title || definition.title,
    filename: overrides.filename || `${definition.id}-report`,
    columns: overrides.columns || definition.columns,
    rows,
    totals,
    metadata: {
      ...buildMetadata(query, user),
      ...(overrides.metadata || {}),
    },
  };

  if (format === 'pdf') {
    writePDF(res, exportOptions);
    return;
  }
  if (format === 'csv') {
    writeCSV(res, exportOptions);
    return;
  }
  await writeExcel(res, exportOptions);
};

const exportReport = async (type, format, query, user, res) => {
  const definition = getReportDefinition(type);
  if (!definition) throw new AppError('Invalid report type', 400);
  await exportDefinition(definition, format, query, user, res);
};

const listTypes = (user) =>
  listReportDefinitions()
    .filter(definition => hasPermission(user.role, definition.requiredPermission))
    .map(({ id, title, description, filters, columns }) => ({
      id,
      title,
      description,
      filters,
      columns: columns.map(({ key, label, type }) => ({ key, label, type })),
    }));

module.exports = {
  exportReport,
  exportDefinition,
  buildReportRows,
  assertReportAccess,
  listTypes,
  handlers: definitions,
};
