export const fontHeading = '"Plus Jakarta Sans", "Noto Sans Devanagari", system-ui, sans-serif';
export const fontBody = '"Source Sans 3", "Noto Sans Devanagari", system-ui, sans-serif';

export const buildTypography = (tokens) => ({
  fontFamily: fontBody,
  htmlFontSize: 16,
  fontSize: 16,
  fontWeightLight: 400,
  fontWeightRegular: 500,
  fontWeightMedium: 600,
  fontWeightBold: 700,
  h1: {
    fontFamily: fontHeading,
    fontWeight: 800,
    fontSize: '2.125rem',
    lineHeight: 1.25,
    letterSpacing: '-0.03em',
    color: tokens.text.primary,
  },
  h2: {
    fontFamily: fontHeading,
    fontWeight: 800,
    fontSize: '1.75rem',
    lineHeight: 1.3,
    letterSpacing: '-0.025em',
    color: tokens.text.primary,
  },
  h3: {
    fontFamily: fontHeading,
    fontWeight: 800,
    fontSize: '1.5rem',
    lineHeight: 1.35,
    letterSpacing: '-0.02em',
    color: tokens.text.primary,
  },
  h4: {
    fontFamily: fontHeading,
    fontWeight: 700,
    fontSize: '1.25rem',
    lineHeight: 1.4,
    letterSpacing: '-0.015em',
    color: tokens.text.primary,
  },
  h5: {
    fontFamily: fontHeading,
    fontWeight: 700,
    fontSize: '1.125rem',
    lineHeight: 1.45,
    color: tokens.text.primary,
  },
  h6: {
    fontFamily: fontHeading,
    fontWeight: 700,
    fontSize: '1rem',
    lineHeight: 1.5,
    color: tokens.text.primary,
  },
  subtitle1: {
    fontFamily: fontHeading,
    fontWeight: 600,
    fontSize: '1rem',
    lineHeight: 1.5,
    color: tokens.text.primary,
  },
  subtitle2: {
    fontFamily: fontHeading,
    fontWeight: 600,
    fontSize: '0.9375rem',
    lineHeight: 1.5,
    color: tokens.text.secondary,
  },
  body1: {
    fontSize: '1rem',
    lineHeight: 1.6,
    fontWeight: 500,
    color: tokens.text.primary,
  },
  body2: {
    fontSize: '0.9375rem',
    lineHeight: 1.55,
    fontWeight: 500,
    color: tokens.text.secondary,
  },
  button: {
    fontFamily: fontHeading,
    fontWeight: 700,
    fontSize: '0.9375rem',
    lineHeight: 1.5,
    letterSpacing: '0.01em',
    textTransform: 'none',
  },
  caption: {
    fontSize: '0.8125rem',
    lineHeight: 1.45,
    fontWeight: 600,
    color: tokens.text.secondary,
  },
  overline: {
    fontFamily: fontHeading,
    fontSize: '0.75rem',
    lineHeight: 1.6,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: tokens.text.secondary,
  },
});
